config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  get 'contact', to: 'pages#contact'
  resources :cocktails do
    resources :doses, only: %i[new create index]
  end
  resources :doses, only: %i[destroy index]
  resources :saved_cocktails, only: %i[index destroy create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  include PgSearch::Model
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo


  belongs_to :user
  # has_many :users, through: :saved_cocktails

  validates :name, presence: true, uniqueness: true

  pg_search_scope :flavor_search, associated_against: {
    ingredients: :name
  }
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/saved_cocktail.rb
class SavedCocktail < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :saved_cocktails
  # has_many :cocktails, through: :saved_cocktails
  has_many :cocktails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_doses, only: %i[show]

  def index
    if params[:query].present?
      @cocktails = Cocktail.flavor_search(params[:query]).collect.to_a
      cocktails_by_name = Cocktail.where('name ILIKE ?', "%#{params[:query]}%").to_a
      @cocktails += cocktails_by_name
    else
      @cocktails = Cocktail.all
    end
  end

  def my_cocktails
    @my_cocktails = Cocktail.where(user: current_user)
    @saved_cocktails = SavedCocktail.where(user: current_user).includes(:cocktail)
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  private

  def find_doses
    @doses = Dose.where(cocktail_id: params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: %i[index create]

  def index
    @dose = Dose.new
    @doses = Dose.where(cocktail_id: params[:cocktail_id])
    render template: 'cocktails/show'
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      @doses = Dose.where(cocktail_id: params[:cocktail_id])
      render template: 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail_id
    @dose.destroy

    redirect_to cocktail_path(@cocktail)
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
end

app/controllers/saved_cocktails_controller.rb
class SavedCocktailsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @my_cocktails = Cocktail.where(user: current_user)
    @saved_cocktails = SavedCocktail.where(user: current_user).includes(:cocktail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/saved_cocktails_helper.rb
module SavedCocktailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <%= f.input :name, placeholder: 'Margarita'%>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-outline-warning btn-submit' %>
<% end %>

app/views/cocktails/_saved_cocktails.html.erb
<h1>Saved Cocktails</h1>

<%= @saved_cocktails.each do |cocktail| %>

  <p><%= cocktail.name %></p>

<% end %>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<head>
  <title>Spirits Journey</title>
  <meta name="description" content="Find your new favorite drink">
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>

<body>
  <div id="carousel-main" class="carousel slide mb-3" data-ride="carousel">

    <div class="carousel-form">
      <h1 style="color: white; font-weight: bold; text-shadow: 1px 1px grey;">Take your Spirits Journey</h1>
      <%= form_tag cocktails_path, class: 'carousel-search-bar', method: :get do %>
        <%= text_field_tag :query, params[:query], class: "search-box p-1", id: "banner-typed-text" %>
        <%= submit_tag "Search", name: nil, class: "btn btn-warning" %>
      <% end %>
      <h5>-- or --</h5>

      <%= link_to 'create your own', new_cocktail_path, class: "btn btn-warning my-3" %>
    </div>


    <ol class="carousel-indicators">
      <li data-target="#carousel-main" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-main" data-slide-to="1"></li>
      <li data-target="#carousel-main" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag("cocktail_1.jpg", class: "d-block w-100", style: "object-fit: cover; object-position: center;", alt: "First slide") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("cocktail_2.jpg", class: "d-block w-100", style: "object-fit: cover; object-position: center;", alt: "Second slide") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("cocktail_3.jpg", class: "d-block w-100", style: "object-fit: cover; object-position: center;", alt: "Third slide") %>
      </div>
    </div>

    <div class="carousel-controls">
      <a class="carousel-control-prev" href="#carousel-main" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-main" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

  <div class="container-fluid">
    <div class="drink-cards-container">
      <% @cocktails.each do |cocktail| %>
        <%= link_to cocktail_path(cocktail), class: "drink-card", "data-aos" => "fade-in", :action => 'go' do %>
            <div class="drink-card-body">
              <h2><%=cocktail.name%></h2>
            </div>
            <% if cocktail.photo.attached? %>
              <%= cl_image_tag(cocktail.photo.key, width: 500, height: 500, crop: "fit")  %>
            <% else %>
              <%= image_tag 'no_image.png' %>
            <% end %>
        <% end %>
      <% end %>
    </div>
  </div>



  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>

</body>

app/views/cocktails/new.html.erb
  <div class="container-new-cocktail">
    <%= render 'cocktails/form', cocktail: @cocktail %>
  </div>

app/views/cocktails/show.html.erb
<style>
  .subheader-white {
    color: white;
    margin-top: 8px;
    border-top: 1px solid orange;
    padding-top: 16px;
    margin-bottom: 16px;
  }

  .text-main {
    font-family: 'Cormorant Garamond', serif;
    font-size: 1.7em;
    text-align: center;
  }

  .text-orange {
    color: #E67E22;
  }

  .text-white {
    color: white;
  }
</style>

<div class="container-fluid p-0" style="display: flex; flex-direction: column;">

  <div class="w-100" style="
    <% if @cocktail.photo.attached? %>
      background: -webkit-linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url(<%="https://res.cloudinary.com/hayatocloud/image/upload/#{@cocktail.photo.key}"%>);
      background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url(<%="https://res.cloudinary.com/hayatocloud/image/upload/#{@cocktail.photo.key}"%>);
    <% end %>
    min-height: 250px;
    background-size: cover;
    background-position: center;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background-repeat: no-repeat;
    flex-grow: 1;
    flex-basis: 
    ">
  </div>
  <div class="container-fluid py-3 px-3" style="display: flex; flex-direction: column; align-items: center; background-color: rgba(0, 0, 0, 0.7); width: 100%;">
    <h1 style="font-size: 2.5em; text-align: center; color: white; margin-bottom: 20px; margin-top: 20px;"> <%= @cocktail.name %> </h1>
    <% @doses.each do |dose| %>
      <div style="display: flex; width: 100%; justify-content: space-between; align-items: center; max-width: 500px;">
        <p class="text-main text-white">
          <%= dose.ingredient.name %>
        </p>

        <div style="border-top: 1px solid white; flex-grow: 1; height: 10px; margin-left: 8px; margin-right: 8px;"></div>

        <p class="text-main text-orange">
          <%= dose.description %>
        </p>
      </div>
    <% end %>
    <h2 class="subheader-white">Cocktail Description:</h2>
    <p class="text-main text-white">
      <%= @cocktail.description %>
    </p>
  </div>
  
</div>




<%# <button id="btn-add-dose">Add an ingredient</button>
<%= render 'doses/form', cocktail: @cocktail, dose: @dose %> %>

<%# <span class="dose-options"> %>
  <%#= link_to dose_path(dose), method: :delete, data: {confirm: 'Delete this ingredient?'} do %>
    <%# <i class="fas fa-trash text-light"></i> %>
  <%# end %>
<%# </span> %>

app/views/doses/_form.html.erb
<%= simple_form_for([cocktail, dose]) do |f| %>
  <%= f.input :description, placeholder: '20ml' %>
  <%= f.association :ingredient, collection: Ingredient.all.order(name: :asc), selected: 1 %>
  <%= f.submit class: 'btn btn-warning' %>
<% end %>

app/views/doses/new.html.erb
<h1>Make a new dose.</h1>

<%= render 'form', cocktail: @cocktail, dose: @dose %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spirits Journey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta name="description" content="Find your new favorite drink">
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= render 'shared/navbar' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container" style="color: white;">
  <h1>Contact</h1>

  <p>Hayato Clarke</p>
  <p>Email: hayatoclarke@gmail.com</p>
  <p>Github: https://www.github.com/drdrongo</p>
  <p>Instagram: https://www.instagram.com/hayayto</p>
  <p>Linkedin: https://www.linkedin.com/hayato-clarke</p>
  <p>More work: http://www.hayatowork.com</p>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <h4>Follow me</h4>
  <ul class="list-inline">
    <li><a href="instagram.com" class="btn-white social-link"><i class="fab fa-instagram">         </i></a></li>
    <li><a href="github.com" class="btn-white social-link"><i class="fab fa-github-square">        </i></a></li>
    <li><a href="facebook.com" class="btn-white social-link"><i class="fab fa-facebook-square">    </i></a></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="navbar-cocktail">
  <div class="navbar-links">
    <%= link_to cocktails_path do %>
      <i class="fas fa-glass-martini-alt"></i>
    <% end %>
  </div>


  <!-- "Hamburger menu" / "Bar icon" to toggle the navigation links -->
  <a href="javascript:void(0);" class="icon" id="hamburger">
    <i class="fa fa-bars"></i>
  </a>
</div>

<div id="myLinks" style="border-bottom: 1px solid orange;">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Contact', contact_path %>
  <% if user_signed_in? %>
    <%= link_to 'My Cocktails', user_path(current_user) %>
    <%= link_to 'New Cocktail', new_cocktail_path %>
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Log In', new_user_session_path %>
    <%= link_to 'Sign Up', new_user_registration_path %>
  <% end %>
</div>

app/views/users/show.html.erb
<ul class="nav nav-pills nav-fill button-selected" id="pills-tab" role="tablist" style="height: 60px; display: flex; align-items: stretch;">
  <li class="nav-item mr-1 p-1" role="presentation">
    <a class="nav-link active" id="pills-created-tab" data-toggle="pill" href="#pills-created" role="tab" aria-controls="pills-created" aria-selected="true">Created Drinks</a>
  </li>
  <li class="nav-item mr-1 p-1" role="presentation">
    <a class="nav-link" id="pills-saved-tab" data-toggle="pill" href="#pills-saved" role="tab" aria-controls="pills-saved" aria-selected="false">Saved Drinks</a>
  </li>
</ul>

<div class="container" style="color: white; display: flex; flex-direction: column; align-items: center;">

  <div class="tab-content d-flex flex-column align-items-center" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-created" role="tabpanel" aria-labelledby="pills-created-tab">
      <h1 style="text-align: center;">My Recipes:</h1>
      <% @my_cocktails.each do |cocktail| %>
        <%= link_to cocktail_path(cocktail) do %>
          <div class="drink-card">
            <h3 style="flex-basis: 60%; padding: 16px; text-align: center;"><%= cocktail.name %></h3>
            

            <% if cocktail.photo.attached? %>
              <%= cl_image_tag(cocktail.photo.key, width: 500, height: 500, crop: "fit", style: "flex-basis: 40%;")  %>
            <% else %>
              <%= image_tag 'no_image.png' %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="tab-pane" id="pills-saved" role="tabpanel" aria-labelledby="pills-saved-tab">
      <h1 style="text-align: center;">Saved Cocktails:</h1>
      <% @saved_cocktails.each do |saved_cocktail| %>
        <%= link_to cocktail_path(saved_cocktail.cocktail) do %>
          <div class="drink-card">
            <h3 style="flex-basis: 60%; padding: 16px; text-align: center;"><%= saved_cocktail.cocktail.name %></h3>

            <% if saved_cocktail.cocktail.photo.attached? %>
              <%= cl_image_tag(saved_cocktail.cocktail.photo.key, width: 500, height: 500, crop: "fit", style: "flex-basis: 40%;")  %>
            <% else %>
              <%= image_tag 'no_image.png' %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>


  

</div>

  